pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "liran86/devops-infra"
    }

    stages {
        stage('Build') {
            steps {
                sh 'pip install -r app/requirements.txt'
            }
        }

        stage('Test') {
            steps {
                sh 'python -m unittest discover -s app -p "*_test.py" || echo "No tests yet"'
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE:$BUILD_NUMBER .'
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh 'echo $PASS | docker login -u $USER --password-stdin'
                    sh 'docker push $DOCKER_IMAGE:$BUILD_NUMBER'
                }
            }
        }
    }
}
